var statesDS = [
   { Code: "AP", Name: "Andhra Pradesh" },
   { Code: "AR", Name: "Arunachal Pradesh" },
   { Code: "AS", Name: "Assam" },
   { Code: "BR", Name: "Bihar" },
   { Code: "CG", Name: "Chhattisgarh" },
   { Code: "Chandigarh", Name: "Chandigarh" },
   { Code: "DN", Name: "Dadra and Nagar Haveli" },
   { Code: "DD", Name: "Daman and Diu" },
   { Code: "DL", Name: "Delhi" },
   { Code: "GA", Name: "Goa" },
   { Code: "GJ", Name: "Gujarat" },
   { Code: "HR", Name: "Haryana" },
   { Code: "HP", Name: "Himachal Pradesh" },
   { Code: "JK", Name: "Jammu and Kashmir" },
   { Code: "JH", Name: "Jharkhand" },
   { Code: "KA", Name: "Karnataka" },
   { Code: "KL", Name: "Kerala" },
   { Code: "MP", Name: "Madhya Pradesh" },
   { Code: "MH", Name: "Maharashtra" },
   { Code: "MN", Name: "Manipur" },
   { Code: "ML", Name: "Meghalaya" },
   { Code: "MZ", Name: "Mizoram" },
   { Code: "NL", Name: "Nagaland" },
   { Code: "OR", Name: "Orissa" },
   { Code: "PB", Name: "Punjab" },
   { Code: "PY", Name: "Pondicherry" },
   { Code: "RJ", Name: "Rajasthan" },
   { Code: "SK", Name: "Sikkim" },
   { Code: "TN", Name: "Tamil Nadu" },
   { Code: "TR", Name: "Tripura" },
   { Code: "UP", Name: "Uttar Pradesh" },
   { Code: "UK", Name: "Uttarakhand" },
   { Code: "WB", Name: "West Bengal" }
];

